### ISSUE TITLE
GPIO functionality

### ISSUE THREAD

**Issue by szwajda** [flipperzero-rs/flipperzero#130]
Is there an yway of controlling gpio using this lib?

**Comment by JarvisCraft** [comment]
Hi there!

There currently are low-level GPIO bindings in the `flipperzero-sy` crate for which there is an [example](https://github.com/flipperzero-rs/flipperzero/blob/main/crates/flipperzero/examples/gpio.rs) available.

**Comment by dcoles** [comment]
I'd like for us to support the [`embedded_hal::digitial`](https://docs.rs/embedded-hal/latest/embedded_hal/digital/) traits in our high-level `flipperzero` API, similar to what was done for [I2C](https://github.com/flipperzero-rs/flipperzero/blob/main/crates/flipperzero/src/gpio/i2c.rs), but this hasn't been implemented yet.
